site_name: trsproc
site_description: A Python library to process Transcriber TRS files
site_author: Gabriele Chingoli
site_url: https://elda-elra.github.io/trsproc/
repo_name: ELDAELRA/trsproc
repo_url: https://github.com/ELDAELRA/trsproc
copyright: Copyright &copy; 2026 ELDA

watch:
  - src

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: latest

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - docs/gen_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_bases: false
            members_order: source
            heading_level: 3
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - redirects:
      redirect_maps: {}
  - mike:
      alias_type: redirect
      redirect_template: null
      deploy_prefix: ''
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

