site_name: trsproc
site_url: https://elda.org/trsproc
repo_url: https://github.com/ELDAELRA/trsproc
repo_name: ELDAELRA/trsproc
site_description: A Python library to process Transcriber TRS files

watch:
  - src

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_bases: false
            members_order: source
            heading_level: 3

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
